version: '3'
services:
  database:
    image: postgres:12.3-alpine
    restart: always
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authen-dev
    volumes:
      - rush-authen-db:/var/lib/postgresql/data

volumes:
  rush-authen-db: